### ISSUE TITLE
Uncaught FirebaseError: Firebase: Error (auth/invalid-api-key).

### ISSUE THREAD

**Issue by B1ackg0d** [dhiant/react-chatGPT-clone#4]
![image](https://user-images.githubusercontent.com/50610732/224916614-02c3c2fd-88d9-4bf9-b927-71b4a958ed85.png)
What can I do to solve this problem?

**Comment by dhiant** [comment]
It's because I forget to put environment files in netlify.
Are you still facing the issue?

**Comment by mycarlos26** [comment]
yes, the problem persists

**Comment by dhiant** [comment]
share your codebase

**Comment by ChinaBigPan** [comment]
I have the same problem

**Comment by sajjadhussain14** [comment]
same error

**Comment by dhiant** [comment]
Please try with these instructions [here](https://stackoverflow.com/questions/54636324/firebase-invalid-api-key-error-in-console)
and once again thoroughly follow my instructions on README.md

If the issue still persists, let me know

**Comment by sajjadhussain14** [comment]
It is not working either.

**Comment by ApiFlier** [comment]
I went to https://console.firebase.google.com/ and created a new project
Then I clicked Get started by adding Firebase to your app -> Then select a webapp -> then give it name -> Then click Register App
That generated all of the config files I needed, then I went to I went to 
client->src->firebase.config.js 
and replaced the const firebaseConfig = { there with the one the file gave me and that worked

Don't forget to go to https://console.firebase.google.com/ and select your project, then select Build, then Authentication, and set that up. You want to enable username and password and google

**Comment by M33ks** [comment]
Don't forget to also go into your project, select Build, then Authentication, and set that up

**Comment by dhiant** [comment]
@M33ks Yup! You need to have your own firebase config file with all the required keys and project ID.

**Comment by zdwork** [comment]
Firebase: Error (auth/configuration-not-found).

**Comment by g7crservice-Binni-kumari** [comment]
> Firebase: Error (auth/configuration-not-found).

Getting the same issue, Have you got any solution for this?

**Comment by g7crservice-Binni-kumari** [comment]
> Please try with these instructions [here](https://stackoverflow.com/questions/54636324/firebase-invalid-api-key-error-in-console) and once again thoroughly follow my instructions on README.md
> 
> If the issue still persists, let me know

getting issue - **400 Bad request** https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=apiKey .

Are you aware of this issue? what could be the possible solution for this?

**Comment by maksudbeg** [comment]
open AI api keys are not available for me
