### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by ApiFlier** [dhiant/react-chatGPT-clone#6]
I cloned the repo, ran npm install from the client and server folders, in the server folder created a .env file and placed my api key in there (Example below), went to the client folder and ran npm start then opened a second telnet session with the linux server, went to the server folder and ran node index.js (Both said they were running) then went to http://localhost:3000/ and just found a blank white screen that says "Talk-Bot" as the <title>

As a side note, Open AI does show the key was last used today

REACT_APP_OPENAI_API_KEY=xx-XXXXXXXXXXXxxxXxxxXxxXXxxxXX

I also tried putting the key like below

REACT_APP_OPENAI_API_KEY = [xx-XXXXXXXXXXXxxxXxxxXxxXXxxxXX]

**Comment by dhiant** [comment]
What is the error? Have you checked the console?

**Comment by ApiFlier** [comment]
Thats a REALLY good question, just started it again and checked console

caught FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (assert.ts:142:1)
    at _assert (assert.ts:167:1)
    at register.ts:68:1
    at Component.instanceFactory (register.ts:95:1)
    at Provider.getOrInitializeService (provider.ts:318:1)
    at Provider.initialize (provider.ts:242:1)
    at initializeAuth (initialize.ts:66:1)
    at getAuth (index.ts:80:1)
    at ./src/firebase.config.js (firebase.config.js:18:1)
    at options.factory (react refresh:6:1)


I went to client->src->firebase.config.js


I went to https://console.firebase.google.com/ and created a new project
Then I clicked Get started by adding Firebase to your app -> Then select a webapp -> then give it name -> Then click Register App
That generated all of the config files I needed, then I went to I went to 
client->src->firebase.config.js 
and replaced the const firebaseConfig = { there with the one the file gave me and that worked
